#=======================================
# LOGGING
#=======================================
quarkus.log.level=INFO
quarkus.log.category."org.jboss.sbomer".level=DEBUG

#=======================================
# APPLICATION
#=======================================

# IMPORTANT: Only watch taskruns with this label
quarkus.operator-sdk.controllers.redhat-image-enhancer-task-reconciler.selector=sbomer.jboss.org/enhancer-type=redhat-enhancer

# The name of the related tekton task applied to the cluster
sbomer.redhat-image-enhancer.task-name=redhat-image-enhancer

# The address the TaskRun uses to reach the storage service
# Default value (Overridden by env variable in Podman/Prod)
sbomer.storage.url=http://localhost:8085

#=======================================
# KAFKA - GLOBAL PRODUCER CONFIG
#=======================================
# These settings apply to ALL outgoing Kafka channels
kafka.apicurio.registry.auto-register=true
kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS}
kafka.apicurio.registry.url=${SCHEMA_REGISTRY_URL}

#=======================================
# KAFKA - CHANNEL DEFINITIONS
#=======================================

# INCOMING

# --- 'enhancement-created' channel ---
mp.messaging.incoming.enhancement-created.topic=enhancement.created
mp.messaging.incoming.enhancement-created.connector=smallrye-kafka
mp.messaging.incoming.enhancement-created.value.deserializer=io.apicurio.registry.serde.avro.AvroKafkaDeserializer
mp.messaging.incoming.enhancement-created.apicurio.registry.url=${SCHEMA_REGISTRY_URL}
mp.messaging.incoming.enhancement-created.apicurio.registry.auto-register=true
mp.messaging.incoming.enhancement-created.apicurio.registry.use-specific-avro-reader=true
mp.messaging.incoming.enhancement-created.group.id=redhat-enhancer

# OUTGOING

# --- 'enhancement-update' channel ---
mp.messaging.outgoing.enhancement-update.topic=enhancement.update
mp.messaging.outgoing.enhancement-update.connector=smallrye-kafka
mp.messaging.outgoing.enhancement-update.value.serializer=io.apicurio.registry.serde.avro.AvroKafkaSerializer
mp.messaging.outgoing.enhancement-update.apicurio.registry.url=${SCHEMA_REGISTRY_URL}
mp.messaging.outgoing.enhancement-update.apicurio.registry.auto-register=true

# --- 'sbomer-errors' channel ---
mp.messaging.outgoing.sbomer-errors.topic=sbomer.errors
mp.messaging.outgoing.sbomer-errors.connector=smallrye-kafka
mp.messaging.outgoing.sbomer-errors.value.serializer=io.apicurio.registry.serde.avro.AvroKafkaSerializer
mp.messaging.outgoing.sbomer-errors.apicurio.registry.url=${SCHEMA_REGISTRY_URL}
mp.messaging.outgoing.sbomer-errors.apicurio.registry.auto-register=true